language: php

php:
  - 7.2

cache:
  directories:
    - node_module

before_install:
  - mysql -e 'CREATE DATABASE testing;'

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate

services:
  - mysql